spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytic-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.jtsp.consumer1.dto.ProductPayload
        session.timeout.ms: 50000

  application:
    name: consumer-1


server:
  port: 8083


